name: Tests JUnit Workflow

on:
  workflow_run:
    workflows: ["Angular Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and test project
      run: cd back && ./mvnw clean install  
