name: JUnit Tests

on:
  workflow_run:
    workflows: ["Angular Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build and test project
      run: cd back && ./mvnw clean install  


